# Generated by Django 5.2 on 2025-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Type', 'Full Type'), ('Part Type', 'Part Type')], default='Full Type', max_length=15),
            preserve_default=False,
        ),
    ]
