# Generated by Django 5.2 on 2025-05-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='imge',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
