# Generated by Django 5.2 on 2025-05-26 08:15

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='imge',
            field=models.ImageField(blank=True, null=True, upload_to=job.models.image_upload),
        ),
    ]
